force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillingCountry__c</fullName>
    <description>The billing country</description>
    <inlineHelpText>The billing country</inlineHelpText>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__PONumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__PONumber__c</fullName>
    <description>The purchase order number</description>
    <inlineHelpText>The purchase order number</inlineHelpText>
    <label>PO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/Apttus_Billing__InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a single item in an invoice</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__Amount__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Amount__c</fullName>
    <description>The item amount</description>
    <inlineHelpText>The item amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__AssetLineItemId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__AssetLineItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated asset line item</description>
    <inlineHelpText>ID of the associated asset line item</inlineHelpText>
    <label>Asset Line Item</label>
    <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__BillingScheduleId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillingScheduleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated billing schedule</description>
    <inlineHelpText>ID of the associated billing schedule</inlineHelpText>
    <label>Billing Schedule</label>
    <referenceTo>Apttus_Billing__BillingSchedule__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__EndDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__EndDate__c</fullName>
    <description>The item end date</description>
    <inlineHelpText>The item end date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__InvoiceId__c</fullName>
    <description>ID of the associated invoice</description>
    <inlineHelpText>ID of the associated invoice</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__Quantity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Quantity__c</fullName>
    <description>The item quantity</description>
    <inlineHelpText>The item quantity</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__StartDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__StartDate__c</fullName>
    <description>The item start date</description>
    <inlineHelpText>The item start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__AssetLineItem__c/Apttus_Config2__AssetLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__AssetLineItem__c/fields/Apttus_CMConfig__AgreementId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__AgreementId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated agreement</description>
    <inlineHelpText>ID of the associated agreement</inlineHelpText>
    <label>Agreement</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Asset Line Items</relationshipLabel>
    <relationshipName>AssetLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__AssetLineItem__c/fields/Apttus_Config2__ChargeType__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ChargeType__c</fullName>
    <description>The charge type  associated with the product or service</description>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Price</fullName>
            </value>
            <value>
                <fullName>License Fee</fullName>
            </value>
            <value>
                <fullName>Subscription Fee</fullName>
            </value>
            <value>
                <fullName>Implementation Fee</fullName>
            </value>
            <value>
                <fullName>Installation Fee</fullName>
            </value>
            <value>
                <fullName>Maintenance Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__AssetLineItem__c/fields/Apttus_QPConfig__ProposalId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__ProposalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated quote/proposal</description>
    <inlineHelpText>ID of the associated quote/proposal</inlineHelpText>
    <label>Quote/Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Asset Line Items</relationshipLabel>
    <relationshipName>AssetLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ChargeType__c/Apttus_Config2__ChargeType__c.object-meta.xml
<CustomObject>
    <description>Represents a type of charge for a product or service.</description>
    <label>Charge Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceLineItemService.cls
public abstract class InvoiceLineItemService {
    public static Map<Id, Apttus_Billing__InvoiceLineItem__c> getInvoiceLineItemMap(
        Set<Id> setInvoiceLineItemId
    ) {
        return new Map<Id, Apttus_Billing__InvoiceLineItem__c>(
            getInvoiceLineItemFromId(setInvoiceLineItemId)
        );
    }

    public static List<Apttus_Billing__InvoiceLineItem__c> getInvoiceLineItemFromId(
        Set<Id> setInvoiceLineItemId
    ) {
        List<Apttus_Billing__InvoiceLineItem__c> listInvoiceLineItem = new List<Apttus_Billing__InvoiceLineItem__c>();
        setInvoiceLineItemId?.remove(null);
        if (!setInvoiceLineItemId.isEmpty()) {
            listInvoiceLineItem = [
                SELECT
                    Id,
                    Name,
                    Apttus_Billing__Amount__c,
                    Apttus_Billing__Quantity__c,
                    Apttus_Billing__StartDate__c,
                    Apttus_Billing__EndDate__c,
                    Apttus_Billing__BillingScheduleId__c,
                    Apttus_Billing__BillingCountry__c,
                    Apttus_Billing__InvoiceId__c,
                    Apttus_Billing__InvoiceId__r.Name,
                    Apttus_Billing__InvoiceId__r.Apttus_Billing__PONumber__c,
                    Apttus_Billing__InvoiceId__r.Apttus_Billing__BillingCountry__c,
                    Apttus_Billing__AssetLineItemId__c,
                    Apttus_Billing__AssetLineItemId__r.Apttus_Config2__ChargeType__c,
                    Apttus_Billing__AssetLineItemId__r.Apttus_QPConfig__ProposalId__c,
                    Apttus_Billing__AssetLineItemId__r.Apttus_QPConfig__ProposalId__r.Apttus_QPConfig__PONumber__c,
                    Apttus_Billing__AssetLineItemId__r.Apttus_CMConfig__AgreementId__c,
                    Apttus_Billing__AssetLineItemId__r.Apttus_CMConfig__AgreementId__r.Apttus_CMConfig__PONumber__c
                FROM Apttus_Billing__InvoiceLineItem__c
                WHERE Id IN :setInvoiceLineItemId
                LIMIT :Constants.SOQL.RowLimit
            ];
        }

        return listInvoiceLineItem;
    }
}