force-app/main/default/objects/Apttus_Config2__TaxCode__c/Apttus_Config2__TaxCode__c.object-meta.xml
<CustomObject>
    <description>Represents a tax code associated with a product or servce</description>
    <label>Tax Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__TaxCode__c/fields/Apttus_Config2__Code__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Code__c</fullName>
    <description>The external tax code</description>
    <inlineHelpText>The external tax code</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxCode__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <description>Tax Rate</description>
    <inlineHelpText>Tax Rate</inlineHelpText>
    <label>Tax Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TaxCodeService.cls
public abstract class TaxCodeService {
    public static List<Apttus_Config2__TaxCode__c> listTaxCode {
        get {
            if (listTaxCode == null) {
                listTaxCode = [
                    SELECT Id, Name, Apttus_Config2__Code__c, Taxrate__c
                    FROM Apttus_Config2__TaxCode__c
                    LIMIT :Constants.SOQL.RowLimit
                ];
            }
            return listTaxCode;
        }
        private set;
    }

    public static Map<Id, Apttus_Config2__TaxCode__c> mapTaxCode {
        get {
            if (mapTaxCode == null) {
                mapTaxCode = new Map<Id, Apttus_Config2__TaxCode__c>(listTaxCode);
            }
            return mapTaxCode;
        }
        private set;
    }
}