force-app/main/default/objects/Apttus__ComplySystemProperties__c/Apttus__ComplySystemProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Comply System properties</description>
    <label>Comply System Properties</label>
</CustomObject>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__InstanceUrl__c.field-meta.xml
<CustomField>
    <fullName>Apttus__InstanceUrl__c</fullName>
    <description>The Salesforce instance url for redirecting to custom pages</description>
    <label>Instance Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__ApprovalsSystemProperties__c/Apttus_Approval__ApprovalsSystemProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Approvals System properties</description>
    <label>Approvals System Properties</label>
</CustomObject>

force-app/main/default/objects/Apttus_Approval__ApprovalsSystemProperties__c/fields/Apttus_Approval__InstanceUrl__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__InstanceUrl__c</fullName>
    <description>The Salesforce instance url for redirecting to custom pages</description>
    <label>Instance Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ConfigSystemProperties__c/Apttus_Config2__ConfigSystemProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration &amp; Pricing System properties. The record should be named as &quot;System Properties&quot;.</description>
    <label>Config System Properties</label>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__ConfigSystemProperties__c/fields/Apttus_Config2__InstanceUrl__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__InstanceUrl__c</fullName>
    <description>The Salesforce instance url</description>
    <inlineHelpText>The url of your Salesforce instance. The instance url will be used to create an absolute url for your custom pages.</inlineHelpText>
    <label>Instance Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__ProposalSystemProperties__c/Apttus_Proposal__ProposalSystemProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Quote/Proposal System properties</description>
    <label>Proposal System Properties</label>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__ProposalSystemProperties__c/fields/Apttus_Proposal__InstanceUrl__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__InstanceUrl__c</fullName>
    <description>The Salesforce instance url</description>
    <label>Instance Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apttus_XApps__XAuthorForExcelSystemProperties__c/Apttus_XApps__XAuthorForExcelSystemProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>X-Author for Excel System properties. The record should be named as &quot;System Properties&quot;</description>
    <label>X-Author For Excel System Properties</label>
</CustomObject>

force-app/main/default/objects/Apttus_XApps__XAuthorForExcelSystemProperties__c/fields/Apttus_XApps__InstanceUrl__c.field-meta.xml
<CustomField>
    <fullName>Apttus_XApps__InstanceUrl__c</fullName>
    <description>The Salesforce instance url for redirecting to custom pages</description>
    <inlineHelpText>The Salesforce instance url for redirecting to custom pages</inlineHelpText>
    <label>Instance Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/SandboxUser__c.object-meta.xml
<CustomObject>
    <description>SandboxUser</description>
    <label>Sandbox User</label>
    <nameField>
        <label>Sandbox User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandbox Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SandboxUser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <inlineHelpText>Email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>FirstName</description>
    <inlineHelpText>FirstName</inlineHelpText>
    <label>FirstName</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>LastName</description>
    <inlineHelpText>LastName</inlineHelpText>
    <label>LastName</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/SanboxName__c.field-meta.xml
<CustomField>
    <fullName>SanboxName__c</fullName>
    <description>SanboxName</description>
    <inlineHelpText>SanboxName</inlineHelpText>
    <label>SanboxName</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <inlineHelpText>UserName</inlineHelpText>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SandboxAfterRefresh.cls
global class SandboxAfterRefresh implements SandboxPostCopy {
    private static final String TimeZoneSidKey = 'Asia/Kolkata';
    private static final String LocaleSidKey = 'en_IN';
    private static final String EmailEncodingKey = 'UTF-8';
    private static final String LanguageLocaleKey = 'en_US';
    global void runApexClass(SandboxContext context) {
        System.debug(LoggingLevel.ERROR, 'MSA organizationId : ' + context.organizationId());
        System.debug(LoggingLevel.ERROR, 'MSA sandboxId : ' + context.sandboxId());
        System.debug(LoggingLevel.ERROR, 'MSA SandBoxname : ' + context.sandboxName());

        updateInstaceURL();
        String sandboxName = context.sandboxName();

        Profile objProfile = [
            SELECT Id, Name
            FROM Profile
            WHERE Name = 'System Administrator'
            LIMIT 1
        ];

        List<User> listUserToInsert = new List<User>();
        for (SandboxUser__c objSandboxUser : [
            SELECT Id, SanboxName__c, Email__c, UserName__c, FirstName__c, LastName__c
            FROM SandboxUser__c
            WHERE SanboxName__c = :sandboxName
        ]) {
            User objUser = new User();
            objUser.ProfileId = objProfile.Id;
            objUser.Email = objSandboxUser.Email__c;
            objUser.Username = objSandboxUser.UserName__c + '.' + sandboxName;
            objUser.FirstName = objSandboxUser.FirstName__c;
            objUser.LastName = objSandboxUser.LastName__c;
            objUser.Alias =
                objSandboxUser.FirstName__c.left(1) + objSandboxUser.LastName__c.left(3);
            objUser.TimeZoneSidKey = TimeZoneSidKey;
            objUser.LocaleSidKey = LocaleSidKey;
            objUser.EmailEncodingKey = EmailEncodingKey;
            objUser.LanguageLocaleKey = LanguageLocaleKey;
            insert objUser;
        }
        insert listUserToInsert;

        Set<Id> setUserId = new Set<Id>();
        for (User objUser : listUserToInsert) {
            System.resetPassword(objUser.Id, true);
            setUserId.add(objUser.Id);
        }

        ResetPasswordJob objBatch = new ResetPasswordJob(setUserId);
        Database.executeBatch(objBatch, objBatch.BATCH_SIZE);
    }

    private static void updateInstaceURL() {
        String instanceURl = URL.getSalesforceBaseUrl().toExternalForm();
        List<Sobject> listSobjectToUpdate = new List<Sobject>();

        for (Apttus__ComplySystemProperties__c objSetting : [
            SELECT Id, Apttus__InstanceUrl__c
            FROM Apttus__ComplySystemProperties__c
        ]) {
            objSetting.Apttus__InstanceUrl__c = instanceURl;
            listSobjectToUpdate.add(objSetting);
        }
        for (Apttus_Proposal__ProposalSystemProperties__c objSetting : [
            SELECT Id, Apttus_Proposal__InstanceUrl__c
            FROM Apttus_Proposal__ProposalSystemProperties__c
        ]) {
            objSetting.Apttus_Proposal__InstanceUrl__c = instanceURl;
            listSobjectToUpdate.add(objSetting);
        }
        for (Apttus_Config2__ConfigSystemProperties__c objSetting : [
            SELECT Id, Apttus_Config2__InstanceUrl__c
            FROM Apttus_Config2__ConfigSystemProperties__c
        ]) {
            objSetting.Apttus_Config2__InstanceUrl__c = instanceURl;
            listSobjectToUpdate.add(objSetting);
        }
        for (Apttus_Approval__ApprovalsSystemProperties__c objSetting : [
            SELECT Id, Apttus_Approval__InstanceUrl__c
            FROM Apttus_Approval__ApprovalsSystemProperties__c
        ]) {
            objSetting.Apttus_Approval__InstanceUrl__c = instanceURl;
            listSobjectToUpdate.add(objSetting);
        }
        for (Apttus_XApps__XAuthorForExcelSystemProperties__c objSetting : [
            SELECT Id, Apttus_XApps__InstanceUrl__c
            FROM Apttus_XApps__XAuthorForExcelSystemProperties__c
        ]) {
            objSetting.Apttus_XApps__InstanceUrl__c = instanceURl;
            listSobjectToUpdate.add(objSetting);
        }
        update listSobjectToUpdate;
    }
}