force-app/main/default/objects/Apttus_Billing__CreditMemoLineItem__c/Apttus_Billing__CreditMemoLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Line Item</label>
    <nameField>
        <displayFormat>CMI-{00000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__CreditMemoLineItem__c/fields/Apttus_Billing__TaxCodeId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__TaxCodeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the Tax Code associated with the product or service. Only applicable for taxable items.</description>
    <inlineHelpText>ID of the Tax Code associated with the product or service. Only applicable for taxable items.</inlineHelpText>
    <label>Tax Code</label>
    <referenceTo>Apttus_Config2__TaxCode__c</referenceTo>
    <relationshipLabel>Credit Memo Line Items</relationshipLabel>
    <relationshipName>CreditMemoLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/Apttus_Billing__InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a single item in an invoice</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__TaxCodeId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__TaxCodeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the Tax Code associated with the product or service. Only applicable for taxable items.</description>
    <inlineHelpText>ID of the Tax Code associated with the product or service. Only applicable for taxable items.</inlineHelpText>
    <label>Tax Code</label>
    <referenceTo>Apttus_Config2__TaxCode__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxBreakup__c/Apttus_Config2__TaxBreakup__c.object-meta.xml
<CustomObject>
    <description>Represents the tax breakup of a product/service</description>
    <label>Tax Breakup</label>
    <nameField>
        <displayFormat>TB-{00000000}</displayFormat>
        <label>Breakup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Breakups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__TaxBreakup__c/fields/Apttus_Config2__LineItemId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__LineItemId__c</fullName>
    <description>ID of the associated line item</description>
    <inlineHelpText>ID of the associated line item</inlineHelpText>
    <label>Line Item</label>
    <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
    <relationshipName>TaxBreakups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxBreakup__c/fields/Apttus_Config2__Sequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Sequence__c</fullName>
    <description>The breakup sequence</description>
    <inlineHelpText>The breakup sequence</inlineHelpText>
    <label>Sequence</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxBreakup__c/fields/Apttus_Config2__TaxAmount__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__TaxAmount__c</fullName>
    <description>The tax amount</description>
    <inlineHelpText>The tax amount</inlineHelpText>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxBreakup__c/fields/Apttus_Config2__TaxRate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__TaxRate__c</fullName>
    <description>The tax rate</description>
    <inlineHelpText>The tax rate</inlineHelpText>
    <label>TaxRate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxCode__c/Apttus_Config2__TaxCode__c.object-meta.xml
<CustomObject>
    <description>Represents a tax code associated with a product or servce</description>
    <label>Tax Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__TaxCode__c/fields/Apttus_Config2__Code__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Code__c</fullName>
    <description>The external tax code</description>
    <inlineHelpText>The external tax code</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__TaxCode__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <description>Tax Rate</description>
    <inlineHelpText>Tax Rate</inlineHelpText>
    <label>Tax Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TaxCallbackService.cls
public class TaxCallbackService {
    private static final Schema.SObjectType INVOICE_LINE_ITEM = Schema.Apttus_Billing__InvoiceLineItem__c.getSObjectType();
    private static final Schema.SObjectType CERDITMEMO_LINE_ITEM = Schema.Apttus_Billing__CreditMemoLineItem__c.getSObjectType();
    private static final String STR_TAX_ERROR_TAXCODE_NOT_FOUND = 'Tax Code was not found';

    public static List<Apttus_Config2.CustomClass.TaxResult> getTaxResult(
        List<Apttus_Config2.CustomClass.TaxInput> listTaxInput
    ) {
        List<Apttus_Config2.CustomClass.TaxInput> listTaxInputInvoice = new List<Apttus_Config2.CustomClass.TaxInput>();
        List<Apttus_Config2.CustomClass.TaxInput> listTaxInputCreditMemo = new List<Apttus_Config2.CustomClass.TaxInput>();
        for (Apttus_Config2.CustomClass.TaxInput objTaxInput : listTaxInput) {
            if (INVOICE_LINE_ITEM == objTaxInput.Item.getSObjectType()) {
                listTaxInputInvoice.add(objTaxInput);
            } else if (CERDITMEMO_LINE_ITEM == objTaxInput.Item.getSObjectType()) {
                listTaxInputCreditMemo.add(objTaxInput);
            }
        }

        List<Apttus_Config2.CustomClass.TaxResult> listTaxResult = new List<Apttus_Config2.CustomClass.TaxResult>();

        if (!listTaxInputInvoice.isEmpty()) {
            listTaxResult.addAll(getTaxResultForAll(listTaxInputInvoice));
        }

        if (!listTaxInputCreditMemo.isEmpty()) {
            listTaxResult.addAll(getTaxResultForAll(listTaxInputCreditMemo));
        }
        return listTaxResult;
    }

    public static List<Apttus_Config2.CustomClass.TaxResult> getTaxResultForAll(
        List<Apttus_Config2.CustomClass.TaxInput> listTaxInput
    ) {
        List<Apttus_Config2.CustomClass.TaxResult> listTaxResult = new List<Apttus_Config2.CustomClass.TaxResult>();

        for (Apttus_Config2.CustomClass.TaxInput objTaxInput : listTaxInput) {
            Apttus_Config2.CustomClass.TaxResult objTaxResult = new Apttus_Config2.CustomClass.TaxResult();
            Apttus_Billing.CustomClass.TaxResultHandback objTaxResultHandback = new Apttus_Billing.CustomClass.TaxResultHandback();
            objTaxResultHandback.lineItem = objTaxInput.Item;

            objTaxResult.Handback = objTaxResultHandback;
            objTaxResult.TaxAmount = 0;
            objTaxResult.TaxBreakups = new List<Apttus_Config2__TaxBreakup__c>();

            Id taxCodeId = (Id) objTaxInput.Item.get('Apttus_Billing__TaxCodeId__c');
            Apttus_Config2__TaxCode__c objTaxCode = TaxCodeService.mapTaxCode.get(taxCodeId);
            if (objTaxCode != null) {
                Apttus_Config2__TaxBreakup__c objTaxBreakup = new Apttus_Config2__TaxBreakup__c();
                objTaxBreakup.Apttus_Config2__Sequence__c = 1;
                objTaxBreakup.Apttus_Config2__LineItemId__c = objTaxInput.Item.Id;
                objTaxBreakup.Apttus_Config2__TaxType__c = objTaxCode.Apttus_Config2__Code__c;
                objTaxBreakup.Apttus_Config2__TaxRate__c = objTaxCode.TaxRate__c;
                objTaxBreakup.Apttus_Config2__TaxAmount__c =
                    objTaxInput.TaxableAmount *
                    objTaxCode.TaxRate__c *
                    0.01;
                objTaxBreakup.Apttus_Config2__TaxAppliesTo__c = Constants.TaxAppliesTo.NetPrice;
                objTaxBreakup.Apttus_Config2__BreakupType__c = Constants.TaxBreakupType.Detail;

                objTaxResult.TaxBreakups.add(objTaxBreakup);
                objTaxResult.TaxAmount += objTaxBreakup.Apttus_Config2__TaxAmount__c;

                System.debug(LoggingLevel.ERROR, 'MSATAX : ' + objTaxBreakup);
            }

            listTaxResult.add(objTaxResult);
        }
        return listTaxResult;
    }
}