force-app/main/default/objects/SandboxUser__c/SandboxUser__c.object-meta.xml
<CustomObject>
    <description>SandboxUser</description>
    <label>Sandbox User</label>
    <nameField>
        <label>Sandbox User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandbox Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SandboxUser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <inlineHelpText>Email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>FirstName</description>
    <inlineHelpText>FirstName</inlineHelpText>
    <label>FirstName</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>LastName</description>
    <inlineHelpText>LastName</inlineHelpText>
    <label>LastName</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/SanboxName__c.field-meta.xml
<CustomField>
    <fullName>SanboxName__c</fullName>
    <description>SanboxName</description>
    <inlineHelpText>SanboxName</inlineHelpText>
    <label>SanboxName</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SandboxUser__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <inlineHelpText>UserName</inlineHelpText>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ResetUserJob.cls
public class ResetUserJob implements Database.Batchable<sObject>, Database.Stateful {
    public final Integer BATCH_SIZE = 1;
    public final String sandboxName;
    public final Set<Id> setUserId;

    public ResetUserJob(String sandboxName) {
        this.sandboxName = sandboxName;
        this.setUserId = new Set<Id>();
    }

    public Database.QueryLocator start(Database.BatchableContext objBatchableContext) {
        String query = 'SELECT Id FROM User ';
        query += ' WHERE FederationIdentifier = \'Reset\' ';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext objBatchableContext, List<sObject> listsObject) {
        List<SandboxUser__c> listSandboxUser = [
            SELECT Id, SanboxName__c, Email__c, UserName__c, FirstName__c, LastName__c
            FROM SandboxUser__c
            WHERE SanboxName__c = :sandboxName
        ];

        List<User> listUserToUpdate = new List<User>();
        List<User> listUser = (List<User>) listsObject;
        for (User objUser : listUser) {
            for (SandboxUser__c objSandboxUser : listSandboxUser) {
                objUser.Email = objSandboxUser.Email__c;
                objUser.FirstName = objSandboxUser.FirstName__c;
                objUser.LastName = objSandboxUser.LastName__c;
                objUser.Alias = objUser.FirstName.left(1) + objUser.LastName.left(3);
            }
            listUserToUpdate.add(objUser);
            setUserId.add(objUser.Id);
        }
        update listUserToUpdate;

        listUserToUpdate = new List<User>();
        for (User objUser : listUser) {
            for (SandboxUser__c objSandboxUser : listSandboxUser) {
                objUser.Username = objSandboxUser.UserName__c + '.' + sandboxName;
            }
            listUserToUpdate.add(objUser);
            setUserId.add(objUser.Id);
        }
        update listUserToUpdate;
    }

    public void finish(Database.BatchableContext BC) {
        ResetPasswordJob objBatch = new ResetPasswordJob(setUserId);
        ID batchprocessid = Database.executeBatch(objBatch, objBatch.BATCH_SIZE);
    }
}