force-app/main/default/objects/Apttus_Billing__CustomNumberingConfigurationSetting__c/Apttus_Billing__CustomNumberingConfigurationSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Schema used to control the creation and maintenance of the various Custom Numbering Settings.</description>
    <label>Custom Numbering Configuration Setting</label>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__CustomNumberingConfigurationSetting__c/fields/Apttus_Billing__FieldFiveEnabled__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__FieldFiveEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</description>
    <inlineHelpText>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</inlineHelpText>
    <label>Field Five Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__CustomNumberingConfigurationSetting__c/fields/Apttus_Billing__FieldFourEnabled__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__FieldFourEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</description>
    <inlineHelpText>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</inlineHelpText>
    <label>Field Four Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__CustomNumberingConfigurationSetting__c/fields/Apttus_Billing__FieldOneEnabled__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__FieldOneEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</description>
    <inlineHelpText>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</inlineHelpText>
    <label>Field One Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__CustomNumberingConfigurationSetting__c/fields/Apttus_Billing__FieldThreeEnabled__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__FieldThreeEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</description>
    <inlineHelpText>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</inlineHelpText>
    <label>Field Three Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__CustomNumberingConfigurationSetting__c/fields/Apttus_Billing__FieldTwoEnabled__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__FieldTwoEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</description>
    <inlineHelpText>Checkbox to determine if this field will be used when constructing and looking up a Custom Number Entry.</inlineHelpText>
    <label>Field Two Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillingCountry__c</fullName>
    <description>The billing country</description>
    <inlineHelpText>The billing country</inlineHelpText>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceNumberingCallback.cls
public with sharing class InvoiceNumberingCallback implements Apttus_Billing.CustomClass.IFacilitateCustomTransactionNumbers {
    public boolean isValidConfiguration(
        Apttus_Billing__CustomNumberingConfigurationSetting__c numberingConfigSettings
    ) {
        System.debug(LoggingLevel.Error, 'MSA in isValidConfiguration');
        System.debug(
            LoggingLevel.Error,
            'MSA in isValidConfiguration : ' + numberingConfigSettings
        );
        if (
            numberingConfigSettings.Apttus_Billing__ObjectType__c.equals(
                Apttus_Billing.CustomClass.CUSTOM_NUMBERING_OBJECT_TYPE_INVOICE
            )
        ) {
            if (
                true == numberingConfigSettings.Apttus_Billing__FieldOneEnabled__c &&
                false == numberingConfigSettings.Apttus_Billing__FieldtwoEnabled__c &&
                false == numberingConfigSettings.Apttus_Billing__FieldThreeEnabled__c &&
                false == numberingConfigSettings.Apttus_Billing__FieldFourEnabled__c &&
                false == numberingConfigSettings.Apttus_Billing__FieldFiveEnabled__c
            ) {
                return true;
            }
        }

        return false;
    }

    public List<List<String>> fetchInvoiceCustomNumberingFieldLists(
        List<Apttus_Billing__Invoice__c> invoices,
        Apttus_Billing__CustomNumberingConfigurationSetting__c customNumberingConfigSetting
    ) {
        System.debug(LoggingLevel.Error, 'MSA in fetchInvoiceCustomNumberingFieldLists');
        System.debug(
            LoggingLevel.Error,
            'MSA in fetchInvoiceCustomNumberingFieldLists : ' + customNumberingConfigSetting
        );
        List<List<String>> fieldLists = new List<List<String>>();
        for (Apttus_Billing__Invoice__c inv : invoices) {
            List<String> fieldList = new List<String>();
            fieldList.add(inv.Apttus_Billing__BillingCountry__c);
            fieldLists.add(fieldList);
        }
        return fieldLists;
    }
}